### ISSUE TITLE
nonunique long form accessions prevent loading data

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/tripal_eutils#167]
I imported bioproject 412476, and selected "create linked records". I then successfully published the Project record. The Biological Sample record, however, was not imported. Publications and organism were also not imported. 

I tried again, with bioproject 167477. This time the one of 2 biosamples also imported, but not much metadata was imported - just the accession number as the name. One empty publication record was imported. No organism.

Am I doing things in the wrong order?

**Comment by bradfordcondon** [comment]
412476: we expect 3 biosamples, 1 organism, 1 publication from the preview.

upon running the importer:

```
Inserting record into Chado: bioproject: 412476
[site http://default] [TRIPAL ERROR] [TRIPAL_EUTILS] Unable to find UID for biosample:SAMD00093090
```

So, it failed loading the first biosample because the accession was non-unique.


with project 167477, we expect 2 biosamples, assembly, an organism, and a pub

```
Calling: tripal_eutils_create_records(bioproject, 167477, 1)
INFO (TRIPAL_EUTILS): Inserting record into Chado: bioproject: 167477
INFO (TRIPAL_EUTILS): Inserting record into Chado: biosample: 2434893
INFO (TRIPAL_EUTILS): Inserting record into Chado: biosample: 2649412
[site http://default] [TRIPAL ERROR] [TRIPAL_EUTILS] Unable to find UID for assembly:GCA_000648675
```

so in both cases, we get an error because we cant identify that accession uniquely.

if we search for the assembly:

https://www.ncbi.nlm.nih.gov/assembly/?term=GCA_000648675
in this cas,e there are "anomalous results".  presumably we can add `filter` parameters to the query and we'd get a single result.


for the biosample:

https://www.ncbi.nlm.nih.gov/biosample/?term=SAMD00093090

interesitly, only 1 result here via the GUI.  how about the API?

**Comment by bradfordcondon** [comment]
ok, NCBI does indeed let us specify the field, just not on a per parameter basis.  Just what we need.

      `$provider->addParam('field', 'accession');` . 

So `SAMD00093090` now returns a single result.

As for the multiple assemblies, we need to add filters in a similar manner.
